.PHONY: generate
generate:
	go run ../../../gKit/sblock-project/sblock/sblocker -s ../dist -f; rm -rf example

.PHONY: pkg
pkg: generate
	echo "TODO: pkg"

.PHONY: prog
prog: generate
	echo "TODO: prog"
